#!/bin/bash

#SBATCH --job-name=environment-setup        # Job name
#SBATCH --output=install_stuff-%j.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=8
#SBATCH --time=24:00:00          # Run time (hh:mm:ss)
#SBATCH --partition=cores_any    # cpu is enough

module load Python/3.12.3-GCCcore-13.3.0

python3 --version

cd ..   #go to main project directory
source .venv/bin/activate   #activate venv

echo "Running on $(hostname):"

pip3 install requests curl_cffi yt-dlp openpyxl