#!/bin/bash

#SBATCH --job-name=environment-setup.out        # Job name
#SBATCH --output=setup-%j.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=8        # Schedule one core
#SBATCH --time=24:00:00          # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=scavenge    # Run on GPU queue
#SBATCH --gres=gpu:a30:1    #install with the h100s (so that hopefully we have the correct versions of all packages to run on them later)

module load Python/3.12.3-GCCcore-13.3.0

python3 --version

cd ..   #go to main project directory

python3 -m venv .venv   #create venv
source .venv/bin/activate   #activate venv
pip3 install --upgrade pip
python -m pip install torch --index-url https://download.pytorch.org/whl/cu126 #first install a compatible torch version (the gpu drivers on the hpc aren't super up-to-date)
pip3 install openai-whisper
python -c "import torch; print(torch.cuda.is_available()); print(torch.cuda.get_device_name(0))"

echo "Running on $(hostname):"
