#!/bin/bash

#SBATCH --job-name=environment-setup.out        # Job name
#SBATCH --output=setup.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=8        # Schedule one core
#SBATCH --time=24:00:00          # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=scavenge    # Run on GPU queue
#SBATCH --gres=gpu:h100:2    #install with the h100s (so that hopefully we have the correct versions of all packages to run on them later)

module load Python/3.12.3-GCCcore-13.3.0

python3 --version

cd ..   #go to main project directory

python3 -m venv .venv   #create venv
source .venv/bin/activate   #activate venv
pip3 install --upgrade pip
pip3 install openai-whisper
python -c "import torch; print(torch.cuda.is_available()); print(torch.cuda.get_device_name(0))"
pip freeze>requirements.txt #create a requirements.txt from the HPC itself, so that we have the correct versions of the packages
#pip3 install -r requirements.txt    #don't install dependencies for now, just whisper to test
#pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cu126

echo "Running on $(hostname):"
