#!/bin/bash

#SBATCH --job-name=environment-setup.out        # Job name
#SBATCH --output=setup-%j.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=8        # Schedule one core
#SBATCH --time=24:00:00          # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=scavenge    # Run on GPU queue
#SBATCH --gres=gpu:a30:1

module load Python/3.12.3-GCCcore-13.3.0

python3 --version

cd ..   #go to main project directory

source .venv/bin/activate   #activate venv

cd src

echo "Running on $(hostname):"
python transcribe.py --model tiny --limit 10